name: ubuntu_release

on:
  push:
    branches: [ fft_fork ]
  pull_request:
    branches: [ fft_fork ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

    - name: Package
      run: cpack -G DEB
      working-directory: ${{github.workspace}}/build

    - uses: actions/upload-artifact@v3
      with:
        name: mytetra_${{github.sha}}.deb
        path: ${{github.workspace}}/build/mytetra*.deb
